// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tryaegoxemlzawegjrzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyeWFlZ294ZW1semF3ZWdqcnpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NzE2NTQsImV4cCI6MjA2OTU0NzY1NH0.3fUo8exNEXud2icO3Lu61LvMo3_0o7p-3bhGO2ed0R8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});